#!/bin/bash -x

# https://wiki.archlinux.org/index.php/HiDPI

DEVICE=$(xrandr | grep -v disconnected | grep connected | cut -d' ' -f1)
SCALE=1.25x1.25
xrandr --output $DEVICE --scale $SCALE
RESOLUTION=$(xrandr | grep eDP | sed 's/^.* \([0-9]*x[0-9]*\).*$/\1/g')
xrandr --output $DEVICE --panning $RESOLUTION

