---
- name: Development packages
  dnf: name={{item}} state=installed
  with_items:
  - gnome-builder
  - gedit-plugins
  - gnome-sudoku
  - "@Development Tools"
  - python-virtualenv
  - python-oauth2client
  - python-pip
  - python-cherrypy
  - postgresql
  - kernel-devel 
  - kernel-headers 
  - gcc 
  - "gcc-c++"
  - intltool
  - gtkmm30-devel
  - enchant-devel
  - libxml2-devel
  - gconf-editor
  - intltool
  - rpmdevtools
  - jq
  - ruby-devel 
  - make
  - rpm-build
  - rubygem-bundler
  - ImageMagick-devel
  - mariadb-devel
  - uwsgi


#- name: Add Elasticsearch repo
#  yum_repository: 
#  name: "elasticsearch-2.x"
#  baseurl: "https://packages.elastic.co/elasticsearch/2.x/centos"
#  description: Elasticsearch repository for 2.x packages
#  gpgcheck: 1
#  gpgkey: https://packages.elastic.co/GPG-KEY-elasticsearch
#  enabled: 1


