---
- name: Download and install the Arabic fonts
  raw: "[ -d /usr/share/fonts/arabic_fonts ] || files/arabic-fonts.sh"
  when: arabic_fonts

- name: Add elastic 5.x repo
  copy: src=files/elastic5.repo dest=/etc/yum.repos.d/
  when: development 
- name: Development packages
  dnf: name={{item}} state=installed
  with_items:
  - gnome-builder
  - gedit-plugins
  - gnome-sudoku
  - "@Development Tools"
  - python3-pip
  - python3-cherrypy
  - redis
  - postgresql
  - kernel-devel 
  - kernel-headers 
  - gcc 
  - "gcc-c++"
  - intltool
  - gtkmm30-devel
  - enchant-devel
  - libxml2-devel
  - gconf-editor
  - intltool
  - rpmdevtools
  - jq
  - ruby-devel 
  - make
  - rpm-build
  - rubygem-bundler
  - ImageMagick-devel
  - mariadb-devel
  - uwsgi
  - java
  - elasticsearch
  when: development

- name: Disable gnome tracker 
  lineinfile: dest={{item.dest}} state=present regexp={{item.regexp}} line={{item.line}} 
  with_items:
  - {dest: '/etc/xdg/autostart/tracker-extract.desktop', regexp: '^X-GNOME-Autostart-enabled=', line: 'X-GNOME-Autostart-enabled=false'}
  - {dest: '/etc/xdg/autostart/tracker-miner-apps.desktop', regexp: '^X-GNOME-Autostart-enabled=', line: 'X-GNOME-Autostart-enabled=false'}
  - {dest: '/etc/xdg/autostart/tracker-miner-fs.desktop', regexp: '^X-GNOME-Autostart-enabled=', line: 'X-GNOME-Autostart-enabled=false'}
  - {dest: '/etc/xdg/autostart/tracker-miner-rss.desktop', regexp: '^X-GNOME-Autostart-enabled=', line: 'X-GNOME-Autostart-enabled=false'}
  - {dest: '/etc/xdg/autostart/tracker-miner-user-guides.desktop', regexp: '^X-GNOME-Autostart-enabled=', line: 'X-GNOME-Autostart-enabled=false'}
  - {dest: '/etc/xdg/autostart/tracker-store.desktop', regexp: '^X-GNOME-Autostart-enabled=', line: 'X-GNOME-Autostart-enabled=false'}
  when: disable_tracker
